POST http://localhost:5000/v1/user/create
content-Type: application/json

{
    "username": "prof",
    "password": "Welcome123!",
    "email": "itz4mesays+12@gmail.com"
}


###
POST http://localhost:5000/v1/user/login
content-Type: application/json

{
    "username": "prof",
    "password": "Deejayfex_123"
}


###
POST http://localhost:5000/v1/user/change-password
content-Type: application/json
authorization-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MjU0NDIyNTAsImV4cCI6MTYyNTUyODY1MH0.LiRwWmyEyAImylvBLsa2nBrFtvF4PsxZA3yLSU98YwY

{
    "current_password": "Welcome123!",
    "new_password": "Deejayfex_123",
    "confirm_password": "Deejayfex_123"
}

###
GET http://localhost:5000/v1/todo/get-all
content-Type: application/json
authorization-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MjU0NTQzMDQsImV4cCI6MTYyNTU0MDcwNH0.TWIv-GhDpzoSwuwAKmth91MOkC3vuBAUUjGp6Xe1c14


###
GET http://localhost:5000/v1/todo/get-single/1
content-Type: application/json
authorization-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MjU0NTQzMDQsImV4cCI6MTYyNTU0MDcwNH0.TWIv-GhDpzoSwuwAKmth91MOkC3vuBAUUjGp6Xe1c14

###
POST http://localhost:5000/v1/todo/create
content-Type: application/json
authorization-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MjU0NTQzMDQsImV4cCI6MTYyNTU0MDcwNH0.TWIv-GhDpzoSwuwAKmth91MOkC3vuBAUUjGp6Xe1c14

{
    "todo_title": "Frontend Development",
    "todo_description": "Develop a frontend for TODO using VueJs",
    "todo_type": "Draft",
    "todo_status": "Pending",
    "start_date": "2021-07-05",
    "end_date": "2021-07-30"
}