POST http://localhost:5000/v1/user/create
content-Type: application/json

{
    "username": "prof",
    "password": "Welcome123!",
    "email": "itz4mesays+12@gmail.com"
}


###
POST http://localhost:5000/v1/user/login
content-Type: application/json

{
    "username": "prof",
    "password": "Deejayfex_123"
}


###
POST http://localhost:5000/v1/user/change-password
content-Type: application/json
authorization-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE2MjU0NDIyNTAsImV4cCI6MTYyNTUyODY1MH0.LiRwWmyEyAImylvBLsa2nBrFtvF4PsxZA3yLSU98YwY

{
    "current_password": "Welcome123!",
    "new_password": "Deejayfex_123",
    "confirm_password": "Deejayfex_123"
}